export const projects = [
  { id: 'eholdup', index: '01', route: '/projects/eholdup', title: 'Project E-HOLDUP', kicker: 'Criminal intelligence analysis', course: 'BCIT · FSCT 8436', tools: ["i2 Analyst's Notebook", 'ArcGIS', 'Excel'], period: '2026', label: 'Training exercise · fictional scenario',
    summary: 'A full intelligence product on a six-incident armed-robbery series against independent jewelers along one corridor: suspect profiling, modus operandi, spatial and temporal pattern analysis, a call-record network built in i2, source reliability assessment, investigative gaps and prioritized recommendations.',
    finding: 'Six robberies in 31 days, five of them within 4.5 km of one residence and all inside a 12:40–15:20 window. One crew, one fence. The file recommends warrants for three men and a search of The Vault.',
    stairs: [
      { title: 'Robbery map', sub: 'Corridor series on a live 3D map of Surrey', tab: 'map' },
      { title: 'People chart', sub: 'Crew, vehicles, devices, organizations · click a figure', tab: 'network' },
      { title: 'Phone network', sub: 'Call-record links between two handsets', tab: 'phones' },
      { title: 'Timeline portals', sub: 'Eighteen events · step inside each one', tab: 'timeline' },
    ] },
  { id: 'surrey-density', index: '02', route: '/projects/surrey-density', title: 'Surrey crime density', kicker: 'Hotspot and change detection', course: 'BCIT · FSCT 8434', tools: ['ArcGIS', 'Kernel density estimation'], period: '2020 data', label: 'Training dataset · 37,159 offences · Surrey geography',
    summary: 'Kernel density surfaces for two four-month periods computed from the full offence file for the training jurisdiction ("Caper Crossroads" — Surrey geography under a placeholder name), then a change surface, period two minus period one. Rebuilt here from the raw points as extruded columns over a 3D map.',
    finding: 'One north-central hotspot dominates both periods (12,193 offences Jan–Apr, 12,546 May–Aug). The change surface shows it intensified while the south stayed flat — the pattern to resource is the same place getting worse, not new places appearing.',
    stairs: [{ title: 'Density surface', sub: 'KDE from 37k real points · two periods and the change', tab: 'map' }] },
  { id: 'green-timbers', index: '03', route: '/projects/green-timbers', title: 'Assaults near Green Timbers', kicker: 'Buffer analysis around an urban park', course: 'BCIT · FSCT 8434', tools: ['ArcGIS'], period: 'Mar–Jul 2020 data', label: 'Training dataset · real point locations',
    summary: 'An 800 m buffer around Green Timbers Urban Forest Park with assault offences symbolized by type, layered against parks, schools, hospitals and rivers, with a count table by offence category.',
    finding: '91 assaults within 800 m of the park in five months, 63 of them common assault and 26 with a weapon. They sit on the streets around the park rather than inside it.',
    stairs: [{ title: '800 m buffer map', sub: 'Assaults by type · live map', tab: 'map' }] },
  { id: 'moss-park', index: '04', route: '/projects/moss-park', title: 'Moss Park CompStat review', kicker: 'Neighbourhood crime and demographics', course: 'Coursework · Toronto Police MCI open data', tools: ['Excel', 'CompStat thresholds', 'Z-scores'], period: '2014–2024', label: 'Toronto neighbourhood 158 · 10,600 incidents',
    summary: 'A neighbourhood-level review of Moss Park, Toronto: household income, household type and age of primary maintainer, eleven years of major-crime-indicator counts for four crime types, CompStat thresholds with standard deviations and Z-scores, and time-of-day and day-of-week patterns.',
    finding: 'Auto theft in 2024 sat 2.56 standard deviations above its five-year mean — the only crime type outside its normal range, and the one a CompStat review escalates. Assault peaks on weekend nights in a neighbourhood that is 60% one-person households.',
    stairs: [{ title: 'Moss Park review', sub: 'Demographics, CompStat thresholds, time patterns', tab: 'overview' }] },
  { id: 'caper', index: '05', route: '/projects/caper', title: 'Offence explorer', kicker: 'Burglary, robbery, auto theft and prostitution layers', course: 'BCIT · FSCT 8434', tools: ['ArcGIS', 'deck.gl', 'MapLibre'], period: '2020 data', label: 'Training dataset · 1,719 geocoded offences',
    summary: 'The layers behind the ArcGIS coursework, mapped live: residential burglary with modus operandi joined by file number, street robbery, auto theft and prostitution offences, with hour-of-day and day-of-week profiles for whatever is switched on.',
    finding: 'Residential burglary is the volume problem (1,411 files). Two-thirds hit unoccupied single-family homes; doors are the way in twice as often as windows, and a third of those doors were left open or insecure — a target-hardening message before a patrol one.',
    stairs: [{ title: 'Offence explorer', sub: 'Four layers over Surrey, then burglary MO', tab: 'map' }] },
  { id: 'dashboard', index: '06', route: '/projects/dashboard', title: 'Surrey B&E dashboard', kicker: 'Break-and-enter files, 2024', course: 'Coursework · dashboard assignment', tools: ['Excel pivots', 'recharts', 'deck.gl'], period: '2024', label: 'Training dataset · 7,644 files',
    summary: 'An interactive rebuild of an Excel dashboard: 7,644 break-and-enter files across five Surrey neighbourhoods, filterable by neighbourhood and status, with monthly trend, damage cost, location type, items stolen, priority, and a day-by-hour heatmap.',
    finding: '7,644 break-and-enter files and $34.6M in damage in 2024, half still open. Guildford/Fleetwood leads on volume, November is the peak month, and single homes are the most common target.',
    stairs: [{ title: 'Dashboard', sub: 'Filterable KPIs, charts and a 3D neighbourhood map', tab: 'overview' }] },
  { id: 'personal', index: '07', route: '/projects/personal', title: 'Personal', kicker: 'Photography and side projects', course: 'Outside work', tools: ['Camera', 'Excel'], period: 'Ongoing', label: 'Personal',
    summary: 'Photographs, mostly Vancouver, hung in the react-three-fiber image gallery, and the macro counter I keep for body-composition goals.',
    stairs: [
      { title: 'Photography', sub: 'Thirteen frames on a reflective floor', tab: 'photos' },
      { title: 'Macro counter', sub: '2,300 kcal cap · 150–200 g protein', tab: 'macros' },
    ] },
]
export const flatDocs = projects.flatMap((p, pi) => p.stairs.map((d, di) => ({ ...d, projectId: p.id, projectIndex: pi, docIndex: di, project: p })))
export const byId = (id) => projects.find((p) => p.id === id)
